package com.flydata.ui.airportCard

val airportNamesMap = mapOf(
    "AAH" to "Aachen",
    "AAL" to "Aalborg",
    "AAQ" to "Anapa",
    "AAR" to "Århus",
    "ABA" to "Abakan",
    "ABE" to "Allentown-Bethlehem-Easton",
    "ABI" to "Abilene",
    "ABQ" to "Albuquerque",
    "ABR" to "Aberdeen",
    "ABS" to "Abu Simbel",
    "ABT" to "Abha",
    "ABZ" to "Aberdeen",
    "ACA" to "Acapulco/Alvarez",
    "ACE" to "Lanzarote",
    "ACH" to "Altenrhein",
    "ACI" to "Alderney",
    "ACO" to "Ascona",
    "ACT" to "Waco",
    "ACV" to "Arcata",
    "ACY" to "Atlantic City",
    "ADA" to "Adana",
    "ADB" to "Izmir",
    "ADD" to "Addis Abeba",
    "ADH" to "Aldan",
    "ADW" to "Camp Springs/Andrews",
    "AER" to "Sochi",
    "AES" to "Ålesund",
    "AEY" to "Akureyri",
    "AFW" to "Fort Worth Alliance",
    "AFY" to "Afyon",
    "AGA" to "Agadir",
    "AGB" to "Augsburg",
    "AGC" to "Pittsburgh/Allegheny",
    "AGE" to "Wangerooge",
    "AGF" to "Agen/La Garenne",
    "AGH" to "Angelholm Helsingborg",
    "AGP" to "Malaga",
    "AGQ" to "Agrinion",
    "AGR" to "Agra/Kheria",
    "AGS" to "Augusta/Budh Field",
    "AHN" to "Athens",
    "AHO" to "Alghero",
    "AHU" to "Al Hoceima",
    "AJA" to "Ajaccio",
    "AJR" to "Arvidsjaur",
    "AKT" to "Akrotiri",
    "AKU" to "Aksu",
    "AKX" to "Aktyubinsk",
    "ALA" to "Almaty",
    "ALC" to "Alicante",
    "ALF" to "Alta",
    "ALI" to "Alice",
    "ALJ" to "Alexander Bay",
    "ALL" to "Albenga",
    "ALN" to "Alton",
    "ALO" to "Waterloo",
    "ALW" to "Walla Walla",
    "ALY" to "Alexandria",
    "AMA" to "Amarillo",
    "AMM" to "Amman",
    "AMS" to "Amsterdam",
    "ANB" to "Anniston",
    "ANC" to "Anchorage",
    "AND" to "Anderson",
    "ANE" to "Angers-Avrille",
    "ANG" to "Angouleme Brie-Champniers",
    "ANK" to "Ankara Etimesgut",
    "ANR" to "Antwerpen",
    "ANX" to "Andenes",
    "AOC" to "Altenburg",
    "AOI" to "Ancona",
    "AOK" to "Karpathos",
    "AOO" to "Altoona",
    "AOR" to "Alor Setar",
    "APF" to "Naples US",
    "APG" to "Aberdeen/Phillips",
    "APN" to "Alpena",
    "AQJ" to "Aqaba",
    "ARH" to "Arkhangelsk",
    "ARN" to "Stockholm",
    "ART" to "Watertown (NY)",
    "ARW" to "Arad",
    "ASE" to "Aspen",
    "ASF" to "Astrakhan",
    "ASM" to "Asmara",
    "ASR" to "Kayseri",
    "ASW" to "Aswan",
    "ATH" to "Athen",
    "ATL" to "Atlanta/William",
    "ATQ" to "Amritsar",
    "ATY" to "Watertown (SD)",
    "AUA" to "Aruba",
    "AUF" to "Auxerre/Moneteau",
    "AUH" to "Abu Dhabi",
    "AUR" to "Aurillac",
    "AUS" to "Austin/Robert M",
    "AVB" to "Aviano",
    "AVL" to "Asheville",
    "AVN" to "Avignon-Caumont",
    "AVP" to "Scranton",
    "AXD" to "Alexandroupolis",
    "AXP" to "Spring Point",
    "AYK" to "Arkalyk",
    "AYT" to "Antalya",
    "AZN" to "Andizhan",
    "AZO" to "Kalamazoo",
    "AZS" to "El Catey",
    "BAE" to "Barcelonnette-Saint-Pons",
    "BAF" to "Westfield/Barnes",
    "BAH" to "Bahrain",
    "BAL" to "Batman",
    "BAY" to "Baia Mare",
    "BBH" to "Barth",
    "BBP" to "Bembridge",
    "BBS" to "Blackbushe",
    "BCM" to "Bacau",
    "BCN" to "Barcelona",
    "BCS" to "Belle Chasse",
    "BCT" to "Boca Raton",
    "BDA" to "Bermuda",
    "BDE" to "Baudette",
    "BDM" to "Balikesir Bandirma",
    "BDR" to "Bridgeport/Igor I.",
    "BDS" to "Brindisi",
    "BDU" to "Bardufoss",
    "BEB" to "Benbecula",
    "BED" to "Bedford",
    "BEG" to "Beograd",
    "BER" to "Berlin",
    "BES" to "Brest",
    "BEV" to "Beer-Sheba",
    "BEX" to "Benson",
    "BEY" to "Beirut",
    "BFD" to "Bradford",
    "BFE" to "Bielefeld",
    "BFF" to "Scottsbluff",
    "BFI" to "Seattle Boeing Field",
    "BFL" to "Bakersfield",
    "BFS" to "Belfast International",
    "BFT" to "Beaufort",
    "BGC" to "Braganca",
    "BGF" to "Bangui",
    "BGI" to "Barbados",
    "BGM" to "Binghamton",
    "BGO" to "Bergen",
    "BGR" to "Bangor",
    "BGY" to "Milano Bergamo",
    "BGZ" to "Braga",
    "BHD" to "Belfast City",
    "BHH" to "Arar",
    "BHK" to "Bukhara",
    "BHM" to "Birmingham US",
    "BHX" to "Birmingham",
    "BHZ" to "Belo Horizonte Tancredo N",
    "BIA" to "Bastia",
    "BIF" to "El Paso Biggs AAF",
    "BIL" to "Billings",
    "BIM" to "Alice Town",
    "BIO" to "Bilbao",
    "BIQ" to "Biarritz",
    "BIS" to "Bismarck",
    "BIX" to "Biloxi/Keesler",
    "BJD" to "Bakkafjordur",
    "BJF" to "Båtsfjord",
    "BJL" to "Banjul/Yundum",
    "BJS" to "Beijing City",
    "BJV" to "Bodrum/Milas",
    "BJZ" to "Badajoz",
    "BKE" to "Baker",
    "BKK" to "Bangkok",
    "BKL" to "Cleveland Burke Lakefront",
    "BKW" to "Beckley",
    "BLA" to "Beauvais-Tille",
    "BLE" to "Borlange",
    "BLI" to "Bellingham",
    "BLK" to "Blackpool",
    "BLL" to "Billund",
    "BLO" to "Blonduos",
    "BLQ" to "Bologna",
    "BLV" to "Belleville",
    "BLX" to "Belluno",
    "BLY" to "Belmullet",
    "BMA" to "Stockholm Bromma",
    "BMG" to "Bloomington",
    "BMR" to "Baltrum",
    "BNA" to "Nashville",
    "BNN" to "Brønnøysund",
    "BOB" to "Bora Bora",
    "BOD" to "Bordeaux",
    "BOF" to "Washington Bolling",
    "BOH" to "Bournemouth",
    "BOI" to "Boise",
    "BOJ" to "Burgas",
    "BOL" to "Ballykelly",
    "BOM" to "Mumbai",
    "BOO" to "Bodø",
    "BOR" to "Belfort/Chaux",
    "BOS" to "Boston Logan Intl",
    "BOU" to "Bourges",
    "BPT" to "Beaumont",
    "BQH" to "Biggin Hill",
    "BQK" to "Brunswick Glynco J",
    "BRE" to "Bremen",
    "BRG" to "Kentucky",
    "BRI" to "Bari",
    "BRL" to "Burlington",
    "BRN" to "Bern-Belp",
    "BRO" to "Brownsville/South Pa",
    "BRQ" to "Brno",
    "BRR" to "Barra",
    "BRS" to "Bristol",
    "BRU" to "Brussel",
    "BRV" to "Bremerhaven",
    "BSB" to "Brasilia",
    "BSL" to "Basel/Mulhouse/Freiburg",
    "BSM" to "Austin",
    "BSR" to "Basrah",
    "BTL" to "Battle Creek",
    "BTM" to "Butte",
    "BTR" to "Baton Rouge",
    "BTS" to "Bratislava",
    "BTV" to "Burlington",
    "BTZ" to "Bursa",
    "BUD" to "Budapest",
    "BUF" to "Buffalo/Greater",
    "BUH" to "Bucuresti Baneasa",
    "BUR" to "Burbank",
    "BVA" to "Paris Beauvais",
    "BVB" to "Boa Vista",
    "BVC" to "Boa Vista",
    "BVE" to "Brive La Gaillarde",
    "BVG" to "Berlevåg",
    "BVY" to "Beverly",
    "BWE" to "Braunschweig",
    "BWF" to "Barrow/Walney Island",
    "BWG" to "Bowling Green/Warren C",
    "BWI" to "Baltimore Washington Intl",
    "BWK" to "Brac",
    "BYH" to "Blytheville",
    "BYI" to "Burley",
    "BYR" to "Laeso",
    "BYS" to "Fort Irwin/Bicycle",
    "BYT" to "Bantry",
    "BYU" to "Bayreuth",
    "BZG" to "Bydgoszcz",
    "BZI" to "Balikesir Edremit-Korfez",
    "BZM" to "Bergen Op Zoom",
    "BZO" to "Bolzano",
    "BZR" to "Beziers-Vias",
    "BZZ" to "Brize Norton",
    "CAE" to "Colimbia Metropolitan",
    "CAG" to "Cagliari",
    "CAI" to "Kairo",
    "CAL" to "Campbeltown",
    "CAR" to "Caribou",
    "CAS" to "Casablanca Anfa",
    "CAX" to "Carlisle",
    "CBG" to "Cambridge",
    "CBP" to "Coimbra",
    "CBU" to "Cottbus",
    "CCF" to "Carcassonne",
    "CCU" to "Kolkata",
    "CCZ" to "Chub Cay, Berry I.",
    "CDC" to "Cedar City",
    "CDF" to "Cortina",
    "CDG" to "Paris Charles de Gaulle",
    "CDN" to "Camden",
    "CEC" to "Crescent City/Mc Namar",
    "CEF" to "Springfield Westover",
    "CEI" to "Chiang Rai",
    "CEL" to "Cape Eleuthera, Eleuthera I.",
    "CEQ" to "Cannes Mandelieu",
    "CER" to "Cherbourg",
    "CET" to "Cholet-Le Pontreau",
    "CEW" to "Crestview/Bob Sike",
    "CFE" to "Clermont-Ferrand",
    "CFN" to "Donegal",
    "CFR" to "Caen",
    "CFU" to "Korfu",
    "CGF" to "Cleveland Cuyahoga",
    "CGH" to "Sao Paulo Congonhas",
    "CGI" to "Cape Girardeau",
    "CGN" to "Køln Bonn",
    "CGX" to "Chicago Merrill",
    "CHA" to "Chattanooga",
    "CHC" to "Christchurch",
    "CHD" to "Chandler/Williams",
    "CHO" to "Charlottesville",
    "CHQ" to "Chania",
    "CHR" to "Chateauroux/Villers",
    "CHS" to "Charleston",
    "CHV" to "Chaves",
    "CIA" to "Roma Ciampino",
    "CID" to "Cedar Rapids",
    "CIH" to "Changzhi",
    "CIU" to "Sault Ste Marie",
    "CJS" to "Ciudad Juarez",
    "CKB" to "Clarksburg",
    "CKZ" to "Canakkale",
    "CLB" to "Castlebar",
    "CLE" to "Cleveland Hopkins",
    "CLL" to "College Station",
    "CLM" to "Port Angeles/Fairchild",
    "CLT" to "Charlotte",
    "CLY" to "Calvi",
    "CMF" to "Chambery",
    "CMH" to "Columbus Port Columbus Intl",
    "CMI" to "Champaign/Willard",
    "CMN" to "Casablanca Mohamed V",
    "CMR" to "Colmar/Houssen",
    "CND" to "Constanta",
    "CNG" to "Cognac/Chateau Bernard",
    "CNM" to "Carlsbad",
    "CNP" to "Nerlerit Inaat/Constable Pynt",
    "CNX" to "Chiang Mai",
    "COF" to "Cocoa",
    "COH" to "Cooch-Behar",
    "COP" to "COSL Pioneer",
    "COS" to "Colorado Springs",
    "COU" to "Colimbia Regional",
    "COV" to "Covilha",
    "COX" to "Congo Town, Andros I.",
    "CPH" to "København",
    "CPT" to "Cape Town",
    "CQF" to "Calais/Dunkerque",
    "CQM" to "Ciudad Real Airport",
    "CRA" to "Craiova",
    "CRI" to "Pittsdown Crooked Island",
    "CRL" to "Brussel Sør/Charleroi",
    "CRP" to "Corpus Christi International",
    "CRV" to "Crotone",
    "CRW" to "Charleston",
    "CRZ" to "Chardzhou",
    "CSB" to "Caransebes",
    "CSF" to "Creil",
    "CSG" to "Columbus Metropolitan",
    "CTA" to "Catania",
    "CTB" to "Cut Bank",
    "CTT" to "Le Castellet",
    "CUF" to "Cuneo/Levaldigi",
    "CUN" to "Cancun",
    "CVF" to "Courchevel",
    "CVO" to "Corvallis",
    "CVS" to "Clovis",
    "CVT" to "Coventry",
    "CVU" to "Corvo",
    "CWL" to "Cardiff",
    "CXL" to "Calexico",
    "CXO" to "Conroe Montgomery",
    "CYS" to "Cheyenne",
    "CZW" to "Czesochowa/Ridniki",
    "DAA" to "Fort Belvoir",
    "DAB" to "Daytona Beach",
    "DAL" to "Dallas Love Field",
    "DAM" to "Damaskus",
    "DAN" to "Danville",
    "DAY" to "Dayton James Cox International",
    "DBQ" to "Dubuque",
    "DBV" to "Dubrovnik",
    "DCA" to "Washington Dc National",
    "DCI" to "Decimomannu",
    "DCM" to "Castres",
    "DCT" to "Duncan Town,Ragged I.",
    "DDC" to "Dodge City",
    "DEB" to "Debrecen",
    "DEC" to "Decatur",
    "DEL" to "New Delhi",
    "DEN" to "Denver",
    "DET" to "Detroit City",
    "DFW" to "Dallas Fort Worth",
    "DGP" to "Daugavpils",
    "DHN" to "Dothan",
    "DHR" to "Den Helder/De Kooy",
    "DIA" to "Doha Airport",
    "DIJ" to "Dijon",
    "DIY" to "Diyarbakir",
    "DJE" to "Djerba",
    "DJU" to "Djupivogur",
    "DLD" to "Geilo",
    "DLE" to "Dole/Tavaux",
    "DLH" to "Duluth",
    "DLM" to "Dalaman",
    "DMA" to "Tucson Davis Monthan AFB",
    "DME" to "Moskva Domodedovo",
    "DMM" to "Dammam",
    "DMN" to "Deming",
    "DND" to "Dundee",
    "DNK" to "Dnepropetrovsk",
    "DNR" to "Dinard",
    "DNZ" to "Denizli/Cardak",
    "DOH" to "Doha",
    "DOL" to "Deauville",
    "DOV" to "Dover-Cheswold",
    "DPE" to "Dieppe/Saint-Aubin",
    "DPN" to "Nordpolen",
    "DRA" to "Draupner",
    "DRI" to "De Ridder/Beaurega",
    "DRS" to "Dresden",
    "DSE" to "Dessie",
    "DSM" to "Des Moines",
    "DTM" to "Dortmund",
    "DUB" to "Dublin",
    "DUJ" to "Dubois/Jefferson",
    "DUR" to "Durban",
    "DUS" to "Dusseldorf",
    "DWC" to "Dubai World Central",
    "DXB" to "Dubai",
    "EAS" to "San Sebastian",
    "EAU" to "Eau Claire",
    "EBJ" to "Esbjerg",
    "EBL" to "Erbil",
    "EBM" to "El Borma",
    "EBU" to "Saint Etienne",
    "ECG" to "Elizabeth City",
    "EDI" to "Edinburgh",
    "EDW" to "Edwards AFB",
    "EEN" to "Keene/Dillant",
    "EFL" to "Kefallinia",
    "EGC" to "Bergerac",
    "EGS" to "Egilsstadir",
    "EIB" to "Eisenach",
    "EIN" to "Eindhoven",
    "EIY" to "Eyn-Yahav Airstrip",
    "EJH" to "Wadi Ad Dawasir",
    "EKA" to "Eureka Murray Field",
    "EKN" to "Elkins",
    "EKO" to "Elko",
    "EKT" to "Eskilstuna",
    "ELD" to "El Dorado/Goodwin",
    "ELH" to "North Eleuthera",
    "ELM" to "Elmira",
    "ELP" to "El Paso",
    "ELQ" to "Dhahran",
    "EMA" to "Nottingham/East Midland",
    "EME" to "Emden",
    "ENC" to "Nancy-Essey",
    "END" to "Enid/Vance AF",
    "ENF" to "Enontekio",
    "ENK" to "Enniskillen/St.Angelo",
    "ENS" to "Enschede",
    "ENW" to "Kenosha",
    "EPK" to "Episkopi",
    "EPL" to "Epinal-Mirecourt",
    "EQI" to "Eday",
    "ERC" to "Erzincan",
    "ERF" to "Erfurt",
    "ERH" to "Errachidia/Mouay Ali Cherif",
    "ERI" to "Erie",
    "ERZ" to "Erzurum",
    "ESB" to "Ankara Esenboga",
    "ESH" to "Shoreham",
    "ESK" to "Eskisehir/Anadolu",
    "ESS" to "Essen",
    "ETH" to "Eilat/J. Hozman Airport",
    "ETZ" to "Metz/Nancy",
    "EUG" to "Eugene",
    "EVE" to "Harstad/Narvik",
    "EVG" to "Sveg",
    "EVN" to "Jerevan",
    "EVV" to "Evansville/Dress Re",
    "EVX" to "Evreux-Fauville",
    "EWB" to "New Bedford",
    "EWN" to "New Bern/Simmons",
    "EWR" to "New York Newark",
    "EXT" to "Exeter",
    "EYW" to "Key West",
    "EZS" to "Elazig",
    "FAB" to "Farnborough",
    "FAE" to "Færøyene",
    "FAG" to "Fagurholsmyri",
    "FAN" to "Farsund",
    "FAO" to "Faro",
    "FAR" to "Fargo/Hector F",
    "FAT" to "Fresno",
    "FAY" to "Fayetteville Municipal",
    "FBG" to "Fort Bragg/Simmons",
    "FCA" to "Kalispell",
    "FCN" to "Nordholz - Naval",
    "FCO" to "Roma Fiumicino",
    "FDE" to "Førde",
    "FDH" to "Friedrichshafen",
    "FEZ" to "Fez",
    "FFD" to "Fairford",
    "FFO" to "Dayton Patterson",
    "FHU" to "Fort Huachuca/Libby AA",
    "FIE" to "Fair Isle",
    "FIN" to "Finnmark",
    "FJE" to "Blåfjell",
    "FLF" to "Flensburg/Schaferhaus",
    "FLG" to "Flagstaff/Pulliam",
    "FLL" to "Fort Lauderdale - Miami",
    "FLO" to "Florence",
    "FLR" to "Firenze",
    "FLV" to "Fort Leavenworth/Sherman",
    "FLW" to "Azorene Flores",
    "FME" to "Fort Meade/Tipton A",
    "FMM" to "Allgau Memmingen",
    "FMO" to "Munster",
    "FNC" to "Funchal",
    "FNI" to "Nimes",
    "FNT" to "Flint/Bishop",
    "FOD" to "Fort Dodge",
    "FOE" to "Topeka",
    "FOG" to "Foggia",
    "FOR" to "Fortaleza",
    "FPM" to "Melun",
    "FPO" to "Freeport/Intl,Grand Bahama I",
    "FPR" to "Fort Pierce/St Lucie",
    "FRA" to "Frankfurt",
    "FRG" to "Farmingdale",
    "FRI" to "Fort Riley/Marshall",
    "FRL" to "Forli",
    "FRO" to "Florø",
    "FRU" to "Manas",
    "FRZ" to "Fritzlar",
    "FSC" to "Figari Corsica",
    "FSD" to "Sioux Falls",
    "FSI" to "Fort Sill/Henry Po",
    "FSM" to "Fort Smith",
    "FSP" to "Floatel Superior",
    "FTW" to "Fort Worth Meacham",
    "FTY" to "Atlanta/Fulton C",
    "FUE" to "Fuerteventura",
    "FUK" to "Fukuoka",
    "FWA" to "Fort Wayne",
    "FWH" to "Fort Worth Carswell",
    "FYV" to "Fayetteville Drake Field",
    "FZO" to "Filton",
    "GAE" to "Gabes",
    "GAF" to "Gafsa",
    "GAL" to "Galena",
    "GAN" to "Gan Island",
    "GBI" to "Grand Bahama",
    "GCI" to "Guernsey",
    "GCK" to "Garden City",
    "GCN" to "Grand Canyon",
    "GDN" to "Gdansk",
    "GDX" to "Magadan/Sokol",
    "GEG" to "Spokane International",
    "GEV" to "Gallivare",
    "GFA" to "Great Falls Malmstrom AFB",
    "GFL" to "Glens Falls/Warren C",
    "GFR" to "Granville",
    "GGG" to "Longview",
    "GGT" to "George Town, Exuma I.",
    "GGW" to "Glasgow US",
    "GHC" to "Bullocks Harbour",
    "GHF" to "Giebelstadt",
    "GHK" to "Gush Katif",
    "GIA" to "Gap-Tallard",
    "GIB" to "Gibraltar/North Fr",
    "GIG" to "Rio De Janeiro Galeao",
    "GIZ" to "Gassim",
    "GJR" to "Gjogur",
    "GKB" to "Bangalore",
    "GKE" to "Geilenkirchen",
    "GLA" to "Glasgow",
    "GLO" to "Gloucestershire",
    "GLZ" to "Breda/Gilze-Rijen",
    "GNB" to "Grenoble",
    "GNV" to "Gainesville/J R Alis",
    "GOA" to "Genova",
    "GOH" to "Nuuk/Godthaab",
    "GOI" to "Goa",
    "GOJ" to "Novgorod",
    "GON" to "Groton",
    "GOT" to "Gøteborg",
    "GOZ" to "Gorna Orechovitsa",
    "GPA" to "Patras/Araxos A",
    "GPT" to "Gulfport/Biloxi R",
    "GRJ" to "George Airport",
    "GRO" to "Girona",
    "GRQ" to "Groningen",
    "GRR" to "Grand Rapids",
    "GRS" to "Grosseto",
    "GRU" to "Sao Paulo Guarulhos",
    "GRW" to "Azorene GRW",
    "GRX" to "Granada",
    "GRY" to "Grimsey",
    "GRZ" to "Graz",
    "GSB" to "Goldsboro/Seymour",
    "GSE" to "Gøteborg Save",
    "GSP" to "Greenville Spartanburg Intl",
    "GTF" to "Great Falls International",
    "GTW" to "Zlin",
    "GUP" to "Gallup/Senator",
    "GUS" to "Peru",
    "GVA" to "Geneve",
    "GVX" to "Gavle",
    "GWO" to "Greenwood Leflore",
    "GWT" to "Westerland/Sylt",
    "GWY" to "Galway Carnmore",
    "GYD" to "Baku",
    "GYY" to "Gary",
    "GZP" to "Alanya/Gazipasa",
    "GZT" to "Gaziantep ",
    "HAA" to "Hasvik",
    "HAD" to "Halmstad",
    "HAJ" to "Hannover",
    "HAM" to "Hamburg",
    "HAQ" to "Hanimaadhoo",
    "HAU" to "Haugesund",
    "HAV" to "Havana",
    "HAW" to "Haverfordwest",
    "HDB" to "Heidelberg",
    "HDF" to "Heringsdorf",
    "HEL" to "Helsinki",
    "HER" to "Heraklion",
    "HFA" to "Haifa",
    "HFD" to "Hartford/Brainard",
    "HFN" to "Hofn/Hornafjordur",
    "HFS" to "Hagfors",
    "HFT" to "Hammerfest",
    "HGL" to "Helgoland-Dune",
    "HGR" to "Hagerstown/Wash. Co",
    "HHN" to "Frankfurt Hahn",
    "HHR" to "Hawthorne",
    "HIB" to "Hibbing/Chisholm",
    "HIF" to "Ogden/Hill AFB",
    "HIJ" to "Hiroshima",
    "HKG" to "Hongkong",
    "HKT" to "Phuket",
    "HKY" to "Hickory",
    "HLF" to "Hultsfred",
    "HLN" to "Helena",
    "HLY" to "Holyhead",
    "HMA" to "Khanty-Mansiysk",
    "HMN" to "Alamogordo",
    "HMR" to "Hamar",
    "HMV" to "Hemavan",
    "HND" to "Tokyo Haneda",
    "HOD" to "Hod",
    "HOF" to "Hail",
    "HOH" to "Hohenems",
    "HON" to "Huron/Howes",
    "HOQ" to "Hof",
    "HOR" to "Azorene Horta",
    "HOU" to "Houston Hobby",
    "HOV" to "Ørsta/Volda",
    "HPN" to "White Plains",
    "HQM" to "Hoquiam/Bowerman",
    "HRD" to "Harstad",
    "HRG" to "Hurghada",
    "HRK" to "Kharkov",
    "HRL" to "Harlingen/Valley I",
    "HRO" to "Harrison/Boone Co",
    "HST" to "Homestead",
    "HSV" to "Huntsville",
    "HTS" to "Huntington",
    "HUA" to "Huntsville/Redstone",
    "HUF" to "Terre Haute",
    "HUV" to "Hudiksvall",
    "HUY" to "Humberside",
    "HVG" to "Honningsvåg",
    "HVK" to "Holmavik",
    "HVN" to "New Haven",
    "HYA" to "Hyannis Barnstable",
    "HYC" to "High Wycombe",
    "HYV" to "Hyvinkaa",
    "HZK" to "Husavik",
    "IAD" to "Washington Dulles ",
    "IAG" to "Niagara Falls",
    "IAH" to "Houston",
    "IAS" to "Iasi",
    "IBZ" to "Ibiza",
    "ICN" to "Seoul Inchon",
    "IDA" to "Idaho Falls/Fanning",
    "IDB" to "Idre",
    "IEG" to "Zielona Gora",
    "IES" to "Riesa-Gohlis",
    "IEV" to "Kyiv Zhulyany",
    "IFJ" to "Isafjordur",
    "IFO" to "Ivano-Frankovsk",
    "IGA" to "Inagua",
    "IGL" to "Izmir Cigli",
    "IIA" to "Inishmaan",
    "IKK" to "Kankakee",
    "IKT" to "Irkutsk",
    "ILF" to "Ilford",
    "ILG" to "Wilmington Greater",
    "ILH" to "Illesheim",
    "ILM" to "Wilmington International",
    "ILY" to "Islay",
    "ILZ" to "Zilina",
    "IND" to "Indianapolis",
    "INI" to "Nis",
    "INK" to "Wink",
    "INN" to "Innsbruck",
    "INQ" to "Inisheer",
    "INT" to "Winston Salem",
    "INV" to "Inverness",
    "IOA" to "Ioannina",
    "IOM" to "Isle Of Man",
    "IOR" to "Inishmore/Kilronan",
    "IPT" to "Williamsport",
    "IRK" to "Kirksville",
    "ISB" to "Islamabad",
    "ISE" to "Isparta/S.Demirel",
    "ISL" to "Istanbul",
    "ISP" to "Islip Long Island",
    "IST" to "Istanbul",
    "IUD" to "Al Udeid",
    "IVL" to "Ivalo",
    "JAC" to "Jackson Hole",
    "JAN" to "Jackson",
    "JAV" to "Ilulissat/Jakobshavn",
    "JAX" to "Jacksonville FL",
    "JBR" to "Jonesboro",
    "JCH" to "Qasigiannguit/Christianshaab",
    "JED" to "Jeddah",
    "JEG" to "Aasiaat/Egedesminde",
    "JEN" to "Julestjernen",
    "JER" to "Jersey",
    "JFK" to "New York/JFK",
    "JFR" to "Paamiut/Frederikshaab",
    "JGO" to "Qeqertarsuaq/Godhavn",
    "JHS" to "Sisimiut/Holsteinsborg",
    "JIK" to "Ikaria",
    "JJN" to "Jinjiang",
    "JJU" to "Qaqortoq/Julianehaab",
    "JKG" to "Jønkøping",
    "JKH" to "Chios",
    "JKT" to "Jakarta",
    "JLN" to "Joplin",
    "JMK" to "Mykonos",
    "JMS" to "Jamestown",
    "JNB" to "Johannesburg",
    "JNN" to "Nanortalik",
    "JNX" to "Naxos",
    "JOE" to "Joensuu",
    "JRK" to "Arsuk",
    "JSH" to "Sitia",
    "JSI" to "Skiathos",
    "JST" to "Johnstown",
    "JSU" to "Maniitsoq",
    "JSY" to "Syros",
    "JTR" to "Santorini",
    "JTY" to "Astypalaia",
    "JUI" to "Juist",
    "JUL" to "Reisen til julestjernen",
    "JXN" to "Jackson/Reynolds",
    "JYV" to "Jyvaskyla",
    "KAJ" to "Kajaani",
    "KAO" to "Kuusamo",
    "KAU" to "Kauhava",
    "KBL" to "Kabul",
    "KBP" to "Kyiv Boryspil",
    "KBV" to "Krabi",
    "KCM" to "Kahramanmaras",
    "KDL" to "Kardla",
    "KDM" to "Kaadedhdhoo",
    "KDO" to "Kadhdhoo",
    "KEF" to "Reykjavik",
    "KEL" to "Kiel",
    "KEM" to "Kemi/Tornio",
    "KES" to "Kelsey",
    "KEV" to "Kuorevesi",
    "KGD" to "Kaliningrad",
    "KGF" to "Karaganda",
    "KGS" to "Kos",
    "KHI" to "Karachi",
    "KHJ" to "Kauhajoki",
    "KID" to "Kristianstad",
    "KIN" to "Kingston Norman Manley",
    "KIR" to "Kerry Farranfore",
    "KIT" to "Kithira",
    "KIV" to "Kishinev",
    "KIX" to "Osaka Kansai",
    "KJK" to "Kortrijk",
    "KKC" to "Khon Kaen",
    "KKN" to "Kirkenes",
    "KKY" to "Kilkenny",
    "KLI" to "Kaiserslautern",
    "KLJ" to "Klaipeda",
    "KLR" to "Kalmar",
    "KLU" to "Klagenfurt",
    "KLV" to "Karlovy Vary",
    "KLX" to "Kalamata",
    "KOI" to "Kirkwall, Orkney Islands",
    "KOJ" to "Kagoshima",
    "KOK" to "Kokkola/Pietarsaari",
    "KRF" to "Kramfors",
    "KRH" to "Redhill",
    "KRK" to "Krakow",
    "KRN" to "Kiruna",
    "KRP" to "Karup",
    "KRR" to "Krasnodar",
    "KRS" to "Kristiansand",
    "KSC" to "Kosice/Barca",
    "KSD" to "Karlstad",
    "KSF" to "Kassel",
    "KSJ" to "Kasos",
    "KSK" to "Karlskoga",
    "KSO" to "Kastoria",
    "KSU" to "Kristiansund",
    "KSW" to "Kiryat Shmona",
    "KSY" to "Kars",
    "KTP" to "Kingston Tinson",
    "KTQ" to "Kitee",
    "KTT" to "Kittila",
    "KTW" to "Katowice",
    "KUA" to "Kuantan",
    "KUL" to "Kuala Lumpur",
    "KUN" to "Kaunas",
    "KUO" to "Kuopio",
    "KUS" to "Kulusuk",
    "KVA" to "Kavala",
    "KVB" to "Skøvde",
    "KVX" to "Kirov",
    "KWI" to "Kuwait",
    "KYA" to "Konya",
    "KZG" to "Kitzingen",
    "KZI" to "Kozani/Filippos",
    "KZN" to "Kazan",
    "KZS" to "Kastelorizo",
    "LAF" to "Lafayette/Purdue U",
    "LAI" to "Lannion",
    "LAL" to "Lakeland",
    "LAN" to "Lansing",
    "LAR" to "Laramie",
    "LAS" to "Las Vegas Mc Carran",
    "LAX" to "Los Angeles",
    "LBA" to "Leeds/Bradford",
    "LBB" to "Lubbock International",
    "LBC" to "Hamburg Lubeck",
    "LBD" to "Khudzhand",
    "LBE" to "Latrobe/Westmore",
    "LBG" to "Le Bourget",
    "LBI" to "Albi",
    "LBL" to "Liberal",
    "LBY" to "La Baule-Escoublac",
    "LCA" to "Larnaca",
    "LCC" to "Lecce/Lepore",
    "LCG" to "La Coruna",
    "LCH" to "Lake Charles",
    "LCJ" to "Lodz",
    "LCK" to "Columbus Rickenbacker",
    "LCV" to "Lucca/Tassignano",
    "LCY" to "London City",
    "LDE" to "Lourdes/Tarbes",
    "LDK" to "Lidkøping",
    "LDV" to "Landivisiau",
    "LDY" to "Londonderry",
    "LEB" to "Lebanon",
    "LED" to "St. Petersburg",
    "LEH" to "Le Havre",
    "LEI" to "Almeria",
    "LEJ" to "Leipzig",
    "LEQ" to "Lands End/St.Just",
    "LEU" to "Seo De Urgel",
    "LEX" to "Lexington",
    "LEY" to "Lelystad",
    "LFI" to "Hampton/Langley",
    "LFT" to "Lafayette",
    "LGA" to "New York La Guardia",
    "LGB" to "Long Beach",
    "LGG" to "Liege",
    "LGO" to "Langeoog",
    "LGW" to "London Gatwick",
    "LHA" to "Lahr",
    "LHE" to "Lahore",
    "LHR" to "London Heathrow",
    "LID" to "Leiden",
    "LIG" to "Limoges",
    "LIL" to "Lille",
    "LIN" to "Milano Linate",
    "LIS" to "Lisboa",
    "LJU" to "Ljubljana",
    "LKL" to "Lakselv",
    "LKN" to "Leknes",
    "LLA" to "Luleå",
    "LME" to "Le Mans-Arnage",
    "LMO" to "Lossiemouth",
    "LMP" to "Lampedusa",
    "LMT" to "Klamath Falls/Kingsley",
    "LNK" to "Lincoln",
    "LNS" to "Lancaster",
    "LNZ" to "Linz",
    "LON" to "London",
    "LOS" to "Lagos",
    "LOU" to "Louisville Bowman Field",
    "LOZ" to "London US",
    "LPA" to "Gran Canaria",
    "LPI" to "Linkøping",
    "LPL" to "Liverpool",
    "LPP" to "Lappeenranta",
    "LPT" to "Lampang",
    "LPX" to "Liepaya",
    "LPY" to "Le Puy/Loudes",
    "LRA" to "Larisa",
    "LRC" to "Laarbruch",
    "LRD" to "Laredo",
    "LRH" to "La Rochelle",
    "LRS" to "Leros",
    "LRT" to "Lorient",
    "LRU" to "Las Cruces",
    "LSE" to "La Crosse",
    "LSF" to "Fort Benning/Lawson A",
    "LSI" to "Shetland",
    "LSV" to "Las Vegas Nellis AFB",
    "LTH" to "Lathorp Wells",
    "LTN" to "London Luton",
    "LTQ" to "Le Touquet/Paris-Plage",
    "LTS" to "Altus",
    "LUG" to "Lugano",
    "LUK" to "Cincinnati",
    "LUX" to "Luxembourg",
    "LUZ" to "Lublin",
    "LVA" to "Laval-Entrammes",
    "LVM" to "Livingston",
    "LVN" to "Låven",
    "LWM" to "Lawrence",
    "LWO" to "Lvov",
    "LWR" to "Leeuwarden",
    "LWT" to "Lewistown",
    "LXR" to "Luxor",
    "LXS" to "Lemnos",
    "LYC" to "Lycksele",
    "LYE" to "Lyneham",
    "LYH" to "Lynchburg",
    "LYN" to "Lyon Bron",
    "LYR" to "Longyearbyen",
    "LYS" to "Lyon",
    "LYU" to "Ely",
    "LYX" to "Lydd",
    "MAA" to "Madras",
    "MAD" to "Madrid",
    "MAF" to "Midland",
    "MAH" to "Menorca",
    "MAN" to "Manchester",
    "MBD" to "Mmabatho",
    "MBJ" to "Montego Bay",
    "MBS" to "Saginaw",
    "MBX" to "Maribor",
    "MCC" to "Sacramento Mcclellan AFB",
    "MCF" to "Tampa Mac Dill AFB",
    "MCI" to "Kansas City",
    "MCM" to "Monte Carlo",
    "MCN" to "Macon",
    "MCO" to "Orlando International",
    "MCQ" to "Miskolc",
    "MCT" to "Muscat",
    "MCU" to "Montlucon-Gueret",
    "MDT" to "Harrisburg",
    "MDW" to "Chicago Midway",
    "MED" to "Medina",
    "MEH" to "Mehamn",
    "MEI" to "Meridian",
    "MEM" to "Memphis",
    "MEN" to "Mende-Brenoux",
    "MER" to "Atwater Castle AFB",
    "MEX" to "Mexico City",
    "MFE" to "Mcallen/Miller I",
    "MFR" to "Medford",
    "MFX" to "Meribel",
    "MGE" to "Marietta",
    "MGM" to "Montgomery Dannelly",
    "MGW" to "Morgantown",
    "MHG" to "Mannheim",
    "MHH" to "Marsh Harbour, Abaco I.",
    "MHK" to "Manhattan",
    "MHP" to "Minsk International 1",
    "MHQ" to "Mariehamn",
    "MHT" to "Manchester US",
    "MHZ" to "Mildenhall",
    "MIA" to "Miami",
    "MIE" to "Muncie",
    "MIK" to "Mikkeli",
    "MIL" to "Milano",
    "MIP" to "Mitzpe-Ramon Airstrip",
    "MIR" to "Monastir",
    "MJF" to "Mosjøen",
    "MJH" to "Madinah/Pr Mohammad Bin Abdula",
    "MJT" to "Mytilini",
    "MJV" to "Murcia",
    "MKA" to "Marianske Lazne",
    "MKC" to "Kansas  Downtown",
    "MKE" to "Milwaukee",
    "MKG" to "Muskegon",
    "MKL" to "Jackson/Mckellar",
    "MKZ" to "Malacca/Batu Ber",
    "MLA" to "Malta",
    "MLB" to "Melbourne US",
    "MLC" to "Mc Alester",
    "MLE" to "Male",
    "MLH" to "Mulhouse",
    "MLI" to "Moline/Quad-Cit",
    "MLN" to "Melilla",
    "MLO" to "Milos",
    "MLU" to "Monroe",
    "MLX" to "Malatya/Erhac",
    "MMA" to "Malmø",
    "MME" to "Teesside",
    "MMK" to "Murmansk",
    "MMU" to "Morristown",
    "MMX" to "Malmø",
    "MNL" to "Manila",
    "MOD" to "Modesto",
    "MOL" to "Molde",
    "MON" to "Mount Cook",
    "MOT" to "Minot",
    "MOW" to "Moskva",
    "MPL" to "Montpellier",
    "MQC" to "Miquelon",
    "MQN" to "Mo i Rana",
    "MQT" to "Marquette",
    "MQY" to "Smyrna",
    "MRB" to "Martinsburg",
    "MRS" to "Marseille",
    "MRU" to "Mauritius",
    "MRY" to "Monterey",
    "MSE" to "Manston",
    "MSN" to "Madison",
    "MSO" to "Missoula",
    "MSP" to "Minneapolis",
    "MSQ" to "Minsk International 2",
    "MSR" to "Mus",
    "MSS" to "Massena/Richards",
    "MST" to "Maastricht",
    "MSY" to "New Orleans",
    "MTN" to "Baltimore/Glenn L Martin",
    "MUC" to "Munchen",
    "MUH" to "Mersa",
    "MUI" to "Fort Indiantown/Muir AAF",
    "MUO" to "Mountain Home AFB",
    "MVQ" to "Mogilev",
    "MVV" to "Megeve",
    "MXF" to "Montgomery Maxwell",
    "MXN" to "Morlaix-Ploujean",
    "MXP" to "Milano Malpensa",
    "MXX" to "Mora",
    "MYG" to "Mayaguana",
    "MYR" to "Myrtle Beach",
    "MYV" to "Marysville/Yuba Cou",
    "NAP" to "Napoli",
    "NAQ" to "Qaanaaq",
    "NAS" to "Nassau",
    "NAW" to "Narathiwat",
    "NBE" to "Enfidha",
    "NBG" to "New Orleans Alvin Callendar",
    "NCE" to "Nice",
    "NCL" to "Newcastle",
    "NCY" to "Annecy",
    "NDB" to "Nouadhibou",
    "NDJ" to "Ndjamena",
    "NDR" to "Nador",
    "NDY" to "Sanday",
    "NDZ" to "Nordholz - Spieka",
    "NEG" to "Negril",
    "NEL" to "Lakehurst/Naec",
    "NET" to "New Bight, Cat I.",
    "NEW" to "New Orleans Lakefront",
    "NFL" to "Fallon/NAS",
    "NGP" to "Corpus Christi NAS",
    "NGS" to "Nagasaki",
    "NGU" to "Norfolk/NAS Cham",
    "NHK" to "Patuxent River/NAS",
    "NHT" to "Northolt",
    "NHZ" to "Brunswick NAS",
    "NIC" to "Nicosia",
    "NIP" to "Jacksonville NAS",
    "NIT" to "Niort/Souche",
    "NKC" to "Nouakchott",
    "NKT" to "Cherry Point",
    "NKX" to "San Diego Miramar",
    "NNA" to "Kenitra",
    "NNG" to "Nanning Wuxu International Air",
    "NNR" to "Connemara",
    "NOC" to "Connaught",
    "NOD" to "Norden-Norddeich",
    "NOF" to "Snøfall",
    "NOR" to "Nordfjordur",
    "NPA" to "Pensacola NAS",
    "NQI" to "Kingsville/NAS",
    "NQJ" to "Gjøa",
    "NQX" to "Key West/NAS",
    "NQY" to "Newquay",
    "NRD" to "Norderney",
    "NRK" to "Norrkøping",
    "NRL" to "North Ronaldsway",
    "NRN" to "Dusseldorf Weeze",
    "NRT" to "Tokyo Narita",
    "NSY" to "Sigonella",
    "NTB" to "Notodden",
    "NTE" to "Nantes",
    "NUE" to "Nurnberg",
    "NUQ" to "Mountain View",
    "NUT" to "Nutuve",
    "NVK" to "Narvik",
    "NVS" to "Nevers/Fourchambault",
    "NWG" to "Gudrun",
    "NWI" to "Norwich",
    "NXX" to "Willow Grove",
    "NYO" to "Stockholm Skavsta ",
    "NZC" to "Jacksonville Cecil Field",
    "NZY" to "San Diego North Island",
    "OAK" to "Oakland - San Francisco",
    "OBF" to "Oberpfaffenhofen",
    "OBL" to "Zoersel",
    "OBS" to "Aubenas-Vals-Lanas",
    "OBY" to "Ittoqqortoormiit/Scoresbysund",
    "OCJ" to "Ocho Rios/Boscobel",
    "ODB" to "Ciudad Real/Almagro",
    "ODE" to "Odense",
    "ODH" to "Odiham",
    "ODS" to "Odessa",
    "OER" to "Ørnskøldsvik",
    "OGD" to "Ogden",
    "OHR" to "Wyk Auf Fohr",
    "OKA" to "Okinawa/Kadena A",
    "OKC" to "Oklahoma City",
    "OLA" to "Ørland",
    "OLB" to "Olbia",
    "OLD" to "Old Town",
    "OLM" to "Olympia",
    "OLO" to "Olomouc",
    "OLU" to "Columbus Municipal NE",
    "OMA" to "Omaha",
    "OMO" to "Mostar",
    "OMR" to "Oradea",
    "OMS" to "Omsk",
    "ONT" to "Ontario",
    "OPA" to "Kopasker",
    "OPO" to "Porto",
    "ORA" to "Al Asud",
    "ORB" to "Ørebro",
    "ORD" to "Chicago OHare",
    "ORE" to "Orleans",
    "ORF" to "Norfolk",
    "ORH" to "Worcester",
    "ORK" to "Cork",
    "ORM" to "Northampton/Sywell",
    "ORY" to "Paris Orly",
    "OSA" to "Osaka",
    "OSD" to "Østersund",
    "OSH" to "Oshkosh",
    "OSI" to "Osijek",
    "OSK" to "Oskarshamn",
    "OSL" to "Oslo",
    "OSP" to "Redzikow",
    "OSR" to "Ostrava",
    "OST" to "Oostende",
    "OSU" to "Columbus Ohio State University",
    "OSY" to "Namsos",
    "OSZ" to "Koszalin",
    "OTH" to "North Bend",
    "OTP" to "Bucuresti Otopeni",
    "OUL" to "Oulu",
    "OVB" to "Novosibirsk ",
    "OVD" to "Asturias",
    "OWB" to "Owensboro-Davies County",
    "OXF" to "Oxford/Kidlington",
    "OZZ" to "Ouarzazate",
    "PAD" to "Paderborn-Lippstadt",
    "PAE" to "Everett Snohomish County",
    "PAH" to "Paducah/Barkley",
    "PAM" to "Panama City Tyndall (US)",
    "PAR" to "Paris",
    "PAS" to "Paros",
    "PAU" to "Pau/Pyrenees",
    "PBG" to "Plattsburgh AFB",
    "PCN" to "Picton/Koromiko",
    "PDG" to "Padang/Tabing",
    "PDK" to "Atlanta/De Kalb",
    "PDL" to "Ponta Delgada Sao Miguel",
    "PDV" to "Plovdiv",
    "PDX" to "Portland",
    "PEF" to "Peenemunde",
    "PEG" to "Perugia",
    "PEK" to "Beijing Capital",
    "PEN" to "Penang",
    "PFJ" to "Patreksfjordur",
    "PFN" to "Panama City Bay County",
    "PFO" to "Paphos",
    "PGF" to "Perpignan",
    "PHF" to "Newport News",
    "PHL" to "Philadelphia",
    "PHX" to "Phoenix",
    "PIA" to "Peoria",
    "PIE" to "St Petersburg-Clearwater (US)",
    "PIH" to "Pocatello",
    "PIK" to "Glasgow Prestwick",
    "PIR" to "Pierre",
    "PIS" to "Poitiers",
    "PIT" to "Pittsburgh",
    "PIW" to "Pikwitonei",
    "PIX" to "Azorene Pico",
    "PKB" to "Parkeresburg/Wood County-GRW",
    "PKH" to "Porto Kheli/Alexion",
    "PLB" to "Plattsburgh Clinton",
    "PLH" to "Plymouth",
    "PLN" to "Pellston",
    "PLQ" to "Palanga",
    "PLU" to "Belo Horizonte Pampulha",
    "PLV" to "Poltava",
    "PLZ" to "Port Elizabeth",
    "PMD" to "Palmdale/Air Forc",
    "PME" to "Portsmouth (UK)",
    "PMF" to "Parma",
    "PMI" to "Palma Mallorca",
    "PMO" to "Palermo",
    "PMV" to "Isla de Margarita",
    "PNA" to "Pamplona",
    "PNH" to "Phnom Penh",
    "PNL" to "Pantelleria",
    "PNR" to "Pointe Noire",
    "PNS" to "Pensacola Regional",
    "PNV" to "Panevezys",
    "POB" to "Fayetteville Pope AFB",
    "POE" to "Fort Polk",
    "POP" to "Puerto Plata",
    "POR" to "Pori",
    "POT" to "Port Antonio",
    "POU" to "Poughkeepsie",
    "POV" to "Presov",
    "POW" to "Portoroz",
    "POX" to "Paris Cergy Pontoise",
    "POZ" to "Poznan",
    "PPW" to "Papa Westray",
    "PRB" to "Paso Robles",
    "PRC" to "Prescott",
    "PRG" to "Praha",
    "PRJ" to "Capri",
    "PRM" to "Portimao",
    "PRN" to "Pristina",
    "PRP" to "Propriano",
    "PRV" to "Prerov",
    "PRX" to "Paris Cox Field (US)",
    "PRY" to "Pretoria",
    "PSA" to "Pisa",
    "PSD" to "Port Said",
    "PSH" to "St Peter",
    "PSM" to "Portsmouth (US)",
    "PSP" to "Palm Springs",
    "PSR" to "Pescara",
    "PTK" to "Pontiac",
    "PUB" to "Pueblo",
    "PUF" to "Pau",
    "PUY" to "Pula",
    "PVD" to "Providence",
    "PVK" to "Preveza/Lefkas",
    "PWM" to "Portland",
    "PWT" to "Bremerton",
    "PXO" to "Porto Santo",
    "PXY" to "Roma Pratica di Mare Mil.",
    "PZE" to "Penzance Heliport",
    "PZY" to "Piestany",
    "QAL" to "Alessandria",
    "QAM" to "Amiens",
    "QCM" to "Como/Idroscalo",
    "QCY" to "Coningsby",
    "QDM" to "Bisha",
    "QEF" to "Egelsbach",
    "QEW" to "Leicester",
    "QFB" to "Freiburg Im Breisgau",
    "QFJ" to "Alluitsup Paa/Sydproven",
    "QFK" to "Selje",
    "QFN" to "Narsaq Kujalleq/Frederiksdal",
    "QFO" to "Duxford",
    "QFQ" to "Måløy",
    "QFR" to "Frosinone",
    "QGO" to "Gorizia",
    "QGY" to "Gyor",
    "QHA" to "Hasselt",
    "QIE" to "Istres-Le Tube",
    "QIF" to "Isleworth",
    "QIZ" to "Bizerte",
    "QJL" to "Kjøllefjord",
    "QJS" to "Saeby/Ottestrup",
    "QKF" to "Krefeld-Egelsberg",
    "QKK" to "Karasjok",
    "QKQ" to "Anklam",
    "QKX" to "Kautokeino",
    "QKZ" to "Konstanz",
    "QLA" to "Lasham",
    "QLF" to "Lahti",
    "QLG" to "Landshut",
    "QLR" to "Leiria",
    "QLS" to "Langenthal",
    "QLT" to "Latina",
    "QMZ" to "Mainz/Finthen",
    "QNC" to "Neuchatel",
    "QNJ" to "Annemasse",
    "QNM" to "Namur/Suarlee",
    "QNX" to "Macon-Charnay",
    "QOB" to "Ansbach-Petersdorf",
    "QOK" to "Øksfjord",
    "QOS" to "Oristano Fenosu",
    "QPA" to "Padova",
    "QPB" to "Campobasso",
    "QPJ" to "Pecs",
    "QPO" to "Potenza",
    "QPZ" to "Piacenza/S.Damiano",
    "QQQ" to "Unknown",
    "QRT" to "Rieti",
    "QRV" to "Arras/Roclincourt",
    "QRY" to "Ikerasassuaq/Prins Chr. Sund",
    "QSA" to "Sabadell",
    "QSR" to "Salerno/Pontecagnano",
    "QST" to "Izmit Topel",
    "QTJ" to "Chartres-Champhol",
    "QTP" to "Tana",
    "QUL" to "Ulm",
    "QUY" to "Wyton",
    "QVA" to "Varese/Venegono",
    "QVD" to "Salo",
    "QVE" to "Forssa",
    "QVF" to "Karkkila",
    "QVK" to "Valkeakoski",
    "QVM" to "Hameenlinna",
    "QVO" to "Kjøllefjord",
    "QVQ" to "Verden-Scharnhorst",
    "QVS" to "Tervakoski",
    "QVT" to "Riihimaki",
    "QVV" to "Heinola",
    "QVW" to "Kotka",
    "QVY" to "Kouvola",
    "QVZ" to "Hamina",
    "QWQ" to "Sheffield City",
    "QWR" to "Donauworth/Genderkingen",
    "QXB" to "Aix-En-Provence ",
    "QXH" to "Schonhagen",
    "QXI" to "Loviisa",
    "QXJ" to "Porvoo",
    "QYC" to "Drachten",
    "QYI" to "Hilversum",
    "QYR" to "Troyes",
    "QYV" to "Deventer/Teuge",
    "QZB" to "Zermatt",
    "QZD" to "Szeged",
    "QZJ" to "Loimaa",
    "QZK" to "Mantsala",
    "QZO" to "Arezzo",
    "QZS" to "Sørøya",
    "QZU" to "Rauma",
    "RAE" to "Al-Baha/Al-Aqiq",
    "RAK" to "Marrakech",
    "RAL" to "Riverside",
    "RAN" to "Ravenna",
    "RAP" to "Rapid City Regional",
    "RBA" to "Rabat",
    "RBL" to "Red Bluff",
    "RBM" to "Straubing-Wallmuhle",
    "RCA" to "Rapid City¨Ellsworth AFB",
    "RCO" to "Rochefort",
    "RCS" to "Rochester (US)",
    "RDD" to "Redding",
    "RDG" to "Reading",
    "RDM" to "Redmond/Roberts",
    "RDU" to "Raleigh/Durham",
    "RDZ" to "Rodez/Marcillac",
    "REB" to "Rechlin-Larz",
    "REE" to "Lubbock Reese AFB",
    "REG" to "Reggio Calabria",
    "RET" to "Røst",
    "REU" to "Reus",
    "RFN" to "Raufarhofn",
    "RHE" to "Reims-Champagne",
    "RHI" to "Rhinelander/Oneida C",
    "RHO" to "Rhodos",
    "RIC" to "Richmond",
    "RIG" to "Rio Grande",
    "RIO" to "Rio De Janeiro/Galeao",
    "RIV" to "Riverside/March AF",
    "RIX" to "Riga",
    "RJK" to "Rijeka",
    "RKE" to "København Roskilde",
    "RKV" to "Reykjavik",
    "RLG" to "Rostock-Laage",
    "RME" to "Rome Griffiss (US)",
    "RMF" to "Marsa Alam",
    "RMG" to "Rome Richard B. Russell (US)",
    "RMI" to "Rimini",
    "RMS" to "Ramstein",
    "RMU" to "Murcia",
    "RNB" to "Rønneby",
    "RNE" to "Roanne-Renaison",
    "RNN" to "Bornholm",
    "RNO" to "Reno",
    "RNS" to "Rennes",
    "RNT" to "Renton",
    "ROA" to "Roanoke",
    "ROC" to "Rochester (UK)",
    "ROM" to "Roma",
    "ROU" to "Rousse",
    "ROW" to "Roswell",
    "RPN" to "Rosh Pina",
    "RRS" to "Røros",
    "RSD" to "Rock Sound/Intl,  Eleuthera I.",
    "RSW" to "Fort Myers/Southwes",
    "RTM" to "Rotterdam",
    "RUH" to "Riyadh",
    "RUT" to "Rutland",
    "RVK" to "Rørvik",
    "RVN" to "Rovaniemi",
    "RWI" to "Rocky Mount",
    "RYG" to "Rygge",
    "RZE" to "Jasionka",
    "SAC" to "Sacramento Executive",
    "SAK" to "Saudarkrokur",
    "SAN" to "San Diego Lindbergh",
    "SAT" to "San Antonio",
    "SAV" to "Savannah Hilton Head",
    "SAW" to "Istanbul Sabiha Gøkcen",
    "SAY" to "Siena",
    "SBA" to "Santa Barbara",
    "SBD" to "San Bernardino Norton AFB",
    "SBN" to "South Bend",
    "SBP" to "San Luis Obispo/",
    "SBS" to "Steamboat Springs",
    "SBY" to "Salisbury-Ocean City",
    "SBZ" to "Sibiu",
    "SCH" to "Schenectady",
    "SCK" to "Stockton",
    "SCN" to "Saarbrucken",
    "SCO" to "Aktau",
    "SCQ" to "Santiago de Compostela",
    "SCR" to "Scandinavian Mountains Airport",
    "SCV" to "Suceava/Salcea",
    "SDF" to "Louisville International",
    "SDL" to "Sundsvall",
    "SDM" to "San Diego Brown Field",
    "SDN" to "Sandane",
    "SDR" to "Santander",
    "SDU" to "Rio De Janeiro Santos Dumont",
    "SDV" to "Tel Aviv Yafo Sde Dov",
    "SEA" to "Seattle",
    "SEL" to "Seoul",
    "SEN" to "London Southend",
    "SEX" to "Sembach Hel",
    "SFB" to "Orlando Sanford",
    "SFF" to "Spokane Felts Field",
    "SFI" to "Safi",
    "SFJ" to "Kangerlussuaq Søndre Strømfj",
    "SFO" to "San Francisco",
    "SFQ" to "Sanliurfa",
    "SFT" to "Skellefteå",
    "SGC" to "Surgut",
    "SGD" to "Sønderborg",
    "SGE" to "Siegen",
    "SGF" to "Springfield Branson",
    "SGH" to "Springfield",
    "SHA" to "Shanghai Hongqiao",
    "SHH" to "Shismaref",
    "SHJ" to "Sharjah",
    "SHR" to "Sheridan",
    "SHV" to "Shreveport",
    "SHW" to "Sharurah",
    "SIC" to "Sinop",
    "SID" to "Sal Island",
    "SIE" to "Sines",
    "SII" to "Sidi Ifni",
    "SIJ" to "Siglufjordur",
    "SIN" to "Singapore Changi",
    "SIP" to "Simferopol",
    "SIR" to "Sion",
    "SJC" to "San Jose",
    "SJJ" to "Sarajevo",
    "SJU" to "San Juan",
    "SJY" to "Seinajoki",
    "SJZ" to "Azorene Sao Jorge",
    "SKA" to "Spokane Fairchild",
    "SKD" to "Samarkand",
    "SKE" to "Skien",
    "SKF" to "San Antonio Kelly AFB",
    "SKG" to "Thessaloniki",
    "SKN" to "Stokmarknes",
    "SKP" to "Skopje",
    "SKS" to "Skrydstrup",
    "SKU" to "Skiros",
    "SKV" to "Santa Katarina",
    "SLC" to "Salt Lake City",
    "SLD" to "Sliac",
    "SLF" to "Sharurah",
    "SLK" to "Saranac Lake",
    "SLM" to "Salamanca",
    "SLN" to "Salina",
    "SMA" to "Azorene Santa Maria",
    "SMF" to "Sacramento International",
    "SMG" to "Skomakergata",
    "SMI" to "Samos",
    "SML" to "Stella Maris",
    "SMV" to "St Moritz",
    "SMW" to "Smara",
    "SMX" to "Santa Maria",
    "SNA" to "Santa Ana",
    "SNG" to "Sør-Norge",
    "SNN" to "Shannon",
    "SNS" to "Salinas",
    "SOB" to "Saarmelleek",
    "SOF" to "Sofia",
    "SOG" to "Sogndal",
    "SOJ" to "Sørkjosen",
    "SOK" to "Sodankyla",
    "SOO" to "Søderhamn",
    "SOU" to "Southampton",
    "SOY" to "Stronsay",
    "SOZ" to "Solenzara",
    "SPA" to "Spartanburg",
    "SPC" to "La Palma",
    "SPI" to "Springfield Capital",
    "SPJ" to "Sparti",
    "SPK" to "Sapporo",
    "SPL" to "Amsterdam",
    "SPM" to "Spangdahlem",
    "SPS" to "Wichita Falls",
    "SPU" to "Split",
    "SQQ" to "Siauliai",
    "SQW" to "Skive",
    "SRP" to "Stord",
    "SRQ" to "Sarasota/Bradenton",
    "SSC" to "Sumter/Shaw AFB",
    "SSH" to "Sharm el Sheik",
    "SSI" to "Brunswick Mckinnon",
    "SSJ" to "Sandnessjøen",
    "SSX" to "Samsun",
    "STA" to "Stauning",
    "STJ" to "St Joseph",
    "STN" to "London Stansted",
    "STO" to "Stockholm/Swedish Air Force",
    "STP" to "St Paul/Downtown",
    "STR" to "Stuttgart",
    "SUB" to "Surabaya",
    "SUF" to "Lamezia/Terme",
    "SUJ" to "Satu Mare",
    "SUU" to "Fairfield/Travis A",
    "SUX" to "Sioux City",
    "SVG" to "Stavanger",
    "SVJ" to "Svolvær",
    "SVL" to "Savonlinna",
    "SVN" to "Savannah Hunter AAF",
    "SVO" to "Moskva Sheremetyevo",
    "SVQ" to "Sevilla",
    "SVX" to "Yekaterinburg",
    "SWF" to "New York/Newburgh",
    "SWO" to "Stillwater",
    "SWS" to "Swansea",
    "SXB" to "Strasbourg Entzheim",
    "SXF" to "Berlin Schonefeld",
    "SXL" to "Sligo",
    "SXZ" to "Siirt",
    "SYG" to "Nordpolen",
    "SYK" to "Stykkisholmur",
    "SYR" to "Syracuse",
    "SYY" to "Stornoway",
    "SZB" to "Kuala Lumpur",
    "SZF" to "Samsun",
    "SZG" to "Salzburg",
    "SZY" to "Szymany",
    "SZZ" to "Szczecin",
    "TAP" to "Tapachula",
    "TAS" to "Tasjkent",
    "TAT" to "Poprad",
    "TAY" to "Tartu",
    "TBJ" to "Tabarka",
    "TBN" to "Fort Leonard Wood/Forney A",
    "TBS" to "Tbilisi",
    "TCB" to "Treasure Cay, Abaco Islands",
    "TCC" to "Tucumcari",
    "TCE" to "Tulcea",
    "TCL" to "Tuscaloosa",
    "TCM" to "Tacoma Mc Chord AFB",
    "TCP" to "Taba",
    "TCS" to "Truth Or Consequences",
    "TEB" to "Teterboro",
    "TED" to "Thisted",
    "TEQ" to "Tekirdag, Corlu",
    "TEY" to "Thingeyri",
    "TFN" to "Tenerife Norte",
    "TFS" to "Tenerife",
    "TGA" to "Tengah",
    "TGD" to "Podgorica",
    "THF" to "Berlin Tempelhof",
    "THN" to "Trollhattan",
    "THO" to "Thorshofn",
    "TIA" to "Tirana",
    "TIF" to "Tabuk",
    "TIP" to "Tripoli",
    "TIV" to "Tivat",
    "TIW" to "Tacoma",
    "TIX" to "Titusville",
    "TJK" to "Tokat",
    "TKU" to "Turku",
    "TLH" to "Tallahassee",
    "TLL" to "Tallinn",
    "TLN" to "Toulon",
    "TLS" to "Toulouse",
    "TLV" to "Tel Aviv Ben Gurion",
    "TMJ" to "Termez",
    "TMP" to "Tampere",
    "TNF" to "Toussus-Le-Noble",
    "TNG" to "Tanger",
    "TOE" to "Tozeur",
    "TOJ" to "Madrid Torrejon",
    "TOL" to "Toledo",
    "TOS" to "Tromsø",
    "TPA" to "Tampa",
    "TPL" to "Temple",
    "TPS" to "Trapani",
    "TRD" to "Trondheim",
    "TRE" to "Tiree",
    "TRF" to "Sandefjord",
    "TRN" to "Torino",
    "TRS" to "Trieste",
    "TSE" to "Akmola",
    "TSF" to "Venezia Treviso",
    "TSR" to "Timisoara",
    "TTB" to "Tortoli",
    "TTN" to "Trenton (US)",
    "TUF" to "Tours",
    "TUI" to "Taif",
    "TUL" to "Tulsa",
    "TUN" to "Tunis",
    "TUP" to "Tupelo",
    "TUS" to "Tucson",
    "TUU" to "Sulayel",
    "TVL" to "South Lake Tahoe",
    "TWF" to "Twin Falls",
    "TXK" to "Texarkana",
    "TXL" to "Berlin Tegel",
    "TYF" to "Torsby",
    "TYM" to "Staniel Cay",
    "TYO" to "Tokyo",
    "TYR" to "Tyler",
    "TZX" to "Trabzon",
    "UAB" to "Adana",
    "UCA" to "Utica",
    "UDE" to "Uden",
    "UIN" to "Quincy",
    "UIP" to "Quimper",
    "UKI" to "Ukiah",
    "ULY" to "Uljanovsk",
    "UMD" to "Uummannaq",
    "UME" to "Umeå",
    "UNN" to "Ranong",
    "UOX" to "Oxford",
    "URD" to "Burg Feuerstein",
    "URE" to "Kuressaare",
    "URO" to "Rouen",
    "UST" to "St Augustine",
    "UTC" to "Utrecht",
    "UTW" to "Queenstown",
    "UVL" to "New Valley/Karga",
    "UZC" to "Uzice",
    "UZH" to "Turaif",
    "VAA" to "Vaasa",
    "VAC" to "Varrelbusch",
    "VAD" to "Valdosta/Moody AF",
    "VAF" to "Valence",
    "VAJ" to "Varna",
    "VAN" to "Van",
    "VAR" to "Varna",
    "VAS" to "Sivas",
    "VAW" to "Vardø",
    "VBG" to "Lompoc Vandenberg AFB",
    "VBS" to "Brescia",
    "VBY" to "Visby",
    "VCE" to "Venezia",
    "VCT" to "Victoria",
    "VDA" to "Ovda",
    "VDB" to "Fagernes",
    "VDP" to "Kolding",
    "VDS" to "Vadsø",
    "VEY" to "Vestmannaeyjar",
    "VGO" to "Vigo",
    "VHM" to "Vilhelmina",
    "VHY" to "Vichy-Charmeil",
    "VIC" to "Vibo Valentia",
    "VIE" to "Wien",
    "VIL" to "Dakhla",
    "VIT" to "Vitoria",
    "VIY" to "Villa Coblay",
    "VKO" to "Moskva Vnukovo",
    "VLC" to "Valencia",
    "VLD" to "Valdosta",
    "VLL" to "Valladolid",
    "VNE" to "Vannes",
    "VNO" to "Vilnius",
    "VOG" to "Volgograd",
    "VOK" to "Camp Douglas Volk Field",
    "VOL" to "Volos/Nea Anch",
    "VPN" to "Vopnafjordur",
    "VPS" to "Valparaiso Eglin AFB",
    "VPZ" to "Valparaiso Porter County",
    "VRA" to "Varadero",
    "VRB" to "Vero Beach",
    "VRK" to "Varkaus",
    "VRL" to "Vila Real",
    "VRN" to "Verona",
    "VRY" to "Værøy",
    "VSE" to "Viseu",
    "VST" to "Vesterås",
    "VTL" to "Vittel-Champ De Courses",
    "VVK" to "Vestervik",
    "VVO" to "Vladivostok",
    "VXO" to "Vaxjo",
    "WAT" to "Waterford",
    "WAW" to "Warszawa",
    "WBG" to "Schleswig",
    "WFK" to "Frenchville",
    "WHS" to "Whalsay",
    "WIC" to "Wick",
    "WIE" to "Wiesbaden",
    "WKR" to "Walker Cay, Abaco I.",
    "WLG" to "Wellington",
    "WMI" to "Warszawa Modlin",
    "WOE" to "Woendrecht",
    "WRL" to "Worland",
    "WRO" to "Wroclaw",
    "WRY" to "Westray",
    "WTD" to "West End, Grand Bahama I.",
    "WTN" to "Waddington",
    "WVB" to "Walvis Bay Namibia",
    "WVN" to "Wilhelmshaven-Mariensiel",
    "WWD" to "Wildwood",
    "WYS" to "West Yellowstone",
    "XAB" to "Abbeville",
    "XAC" to "Arcachon",
    "XAK" to "Herning",
    "XAM" to "Amboise/Dierre",
    "XAN" to "Alencon-Valframbert",
    "XAS" to "Ales-Deaux",
    "XAV" to "Albertville",
    "XBF" to "Bellegarde",
    "XBQ" to "Blois-Le Breuil",
    "XBV" to "Beaune",
    "XBX" to "Bernay-Saint-Martin",
    "XCP" to "Compiegne/Margny",
    "XCW" to "Chaumont Semoutiers",
    "XCX" to "Chatellerault/Targe",
    "XCY" to "Chateau-Thierry-Belleau",
    "XCZ" to "Charleville-Mezieres",
    "XDA" to "Dax/Seyresse",
    "XDK" to "Dunkerque-Ghyvelde",
    "XED" to "Epernay-Plivot",
    "XFE" to "Parent",
    "XFV" to "Brantford",
    "XGT" to "Gueret/Saint-Laurent",
    "XHE" to "Hyeres-Le Palyvestre",
    "XKS" to "Kasabonika",
    "XLE" to "Lens-Benifontaine",
    "XLG" to "Lognes-Emerainville",
    "XLL" to "Lons Le Saunier/Courlaoux",
    "XLN" to "Laon/Chambry",
    "XLR" to "Libourne/Artiques De Lussac",
    "XLW" to "Lemwerder",
    "XME" to "Maubeuge/Elesmes",
    "XMF" to "Montbeliard-Courcelles",
    "XMK" to "Montelimar-Ancone",
    "XMS" to "Marmande/Virazeil",
    "XMW" to "Montauban",
    "XNA" to "Narbonne",
    "XNM" to "Nottingham",
    "XOG" to "Orange-Caritat",
    "XQH" to "Derby",
    "XRN" to "Redon/Bains-Sur-Oust",
    "XRO" to "La Roche-Sur-Yon-Les Ajoncs",
    "XRY" to "Jerez",
    "XSL" to "Sarlat/Domme",
    "XSN" to "Saint-Yan",
    "XSP" to "Singapore Seletar",
    "XSS" to "Soissons-Courmelles",
    "XST" to "Saintes-Thenac",
    "XSV" to "Saverne-Steinbourg",
    "XSW" to "Sedan-Douzy",
    "XTH" to "Thionville/Yutz",
    "XVI" to "Vienne/Reventin",
    "XVN" to "Verdun/Rozelier",
    "XVO" to "Vesoul-Frotey",
    "XVS" to "Valenciennes/Denain",
    "XVZ" to "Vierzon-Mereau",
    "XXP" to "Potsdam",
    "XXX" to "Unknown",
    "XYT" to "Toulouse-Montaudran",
    "YAW" to "Halifax Shearwater",
    "YAY" to "St Anthony",
    "YAZ" to "Tofino",
    "YBE" to "Uranium City",
    "YBR" to "Brandon",
    "YBY" to "Bonnyville",
    "YCD" to "Nanaimo",
    "YCG" to "Castlegar",
    "YCL" to "Charlo",
    "YCM" to "St Catharines",
    "YCN" to "Cochrane",
    "YCT" to "Coronation",
    "YCW" to "Chilliwack",
    "YCX" to "Gagetown.B.",
    "YDB" to "Burwash",
    "YDG" to "Digby",
    "YDN" to "Dauphin",
    "YDP" to "Nain",
    "YEG" to "Edmonton",
    "YEO" to "Yeovilton",
    "YET" to "Edson",
    "YEU" to "Eureka",
    "YFC" to "Fredericton",
    "YFE" to "Forestville",
    "YGK" to "Kingston CA",
    "YGP" to "Gaspeue.",
    "YGQ" to "Geraldtonn",
    "YGX" to "Gillam",
    "YGZ" to "Grise Fiord.W.T.",
    "YHE" to "Hope",
    "YHI" to "Holman.W.T.",
    "YHM" to "Hamiltonn",
    "YHO" to "Hopedale",
    "YHZ" to "Halifax ",
    "YIP" to "Detroit Willow Run",
    "YJT" to "Stephenville",
    "YKG" to "Kangirsuk",
    "YKL" to "Schefferville",
    "YKM" to "Yakima",
    "YKN" to "Yankton",
    "YKQ" to "Waskaganish",
    "YKZ" to "Toronto Buttonville",
    "YLC" to "Kimmirut",
    "YLD" to "Chapleau",
    "YLI" to "Ylivieska",
    "YLL" to "Lloydminster",
    "YLO" to "Shilo",
    "YLW" to "Kelowna",
    "YMA" to "Mayo",
    "YMN" to "Makkovik",
    "YNA" to "Natashquan",
    "YNE" to "Norway House",
    "YNG" to "Youngstown",
    "YNM" to "Matagami",
    "YNS" to "Nemiscau",
    "YOA" to "Koala Nwt",
    "YOC" to "Old Crow",
    "YOH" to "Oxford House",
    "YOO" to "Oshawa",
    "YOW" to "Ottawa/Macd.-Cartier",
    "YOY" to "Valcartier",
    "YPA" to "Prince Albert",
    "YPC" to "Paulatuk.W.T.",
    "YPM" to "Pikangikum",
    "YPO" to "Peawanuck",
    "YPQ" to "Peterborough",
    "YQA" to "Muskoka",
    "YQB" to "Quebec/Jean Lesage",
    "YQC" to "Quaqtaq",
    "YQG" to "Windsor",
    "YQI" to "Yarmouth",
    "YQK" to "Kenora",
    "YQL" to "Lethbridge",
    "YQM" to "Moncton",
    "YQN" to "Nakina",
    "YQQ" to "Comox",
    "YQS" to "St Thomas",
    "YQT" to "Thunder Bay",
    "YQX" to "Gander",
    "YQY" to "Sydney",
    "YQZ" to "Quesnel",
    "YRF" to "Cartwright",
    "YRJ" to "Roberval",
    "YRO" to "Ottawa Rockcliffe",
    "YRV" to "Revelstoke",
    "YSB" to "Sudbury",
    "YSC" to "Sherbrooke",
    "YSD" to "Suffield",
    "YSE" to "Squamish",
    "YSK" to "Sanikiluaq",
    "YSR" to "Nanisivik.W.T.",
    "YSU" to "Summerside",
    "YTA" to "Pembroke",
    "YTR" to "Trenton (CA)",
    "YTS" to "Timmins",
    "YUM" to "Yuma",
    "YVB" to "Bonaventure",
    "YVE" to "Vernon",
    "YVG" to "Vermillion",
    "YVQ" to "Norman Wells ",
    "YVR" to "Vancouver",
    "YVV" to "Wiarton",
    "YWA" to "Petawawa",
    "YWG" to "Winnipeg",
    "YWJ" to "Deline",
    "YWK" to "Wabush",
    "YWO" to "Lupin",
    "YWP" to "Webquie",
    "YWY" to "Wrigley",
    "YXC" to "Cranbrook",
    "YXD" to "Edmonton City Center Airport",
    "YXK" to "Rimouski",
    "YXP" to "Pangnirtung",
    "YXU" to "London CA",
    "YXX" to "Abbotsford",
    "YXY" to "Whitehorse",
    "YXZ" to "Wawa",
    "YYC" to "Calgary",
    "YYD" to "Smithers",
    "YYF" to "Penticton",
    "YYG" to "Charlottetown",
    "YYJ" to "Victoria",
    "YYM" to "Cowley",
    "YYR" to "Goose Bay",
    "YYU" to "Kapuskasing",
    "YYY" to "Mont-Joli",
    "YYZ" to "Toronto Lester B. Pearson",
    "YZF" to "Yellowknife",
    "YZG" to "Salluit",
    "YZP" to "Sandspit",
    "YZR" to "Sarnia",
    "YZU" to "Whitecourt",
    "YZW" to "Teslin",
    "YZX" to "Greenwood CA",
    "ZAD" to "Zadar",
    "ZAG" to "Zagreb",
    "ZAH" to "Zahedan",
    "ZAO" to "Cahors/Lalbenque",
    "ZAV" to "Aveiro",
    "ZAZ" to "Zaragoza",
    "ZBE" to "Zabreh",
    "ZBF" to "Bathurst",
    "ZBM" to "Bromont",
    "ZBQ" to "Randers",
    "ZCA" to "Arnsberg",
    "ZCB" to "Aschaffenburg-Grossostheim",
    "ZCC" to "Baden Baden",
    "ZCD" to "Bamberg",
    "ZCN" to "Celle",
    "ZCR" to "Dachau/Grobenried",
    "ZCV" to "Dinslaken Schwarze Heide",
    "ZDK" to "Biel-Kappelen",
    "ZEE" to "Fulda-Jossa",
    "ZFA" to "Faro",
    "ZGA" to "Gera-Leumnitz",
    "ZGO" to "Gotha-Ost",
    "ZGQ" to "Tournai",
    "ZHH" to "Gossau Sg",
    "ZHI" to "Grenchen",
    "ZHK" to "Gstaad-Inn Grund",
    "ZHW" to "La Cote",
    "ZIA" to "Trento",
    "ZIH" to "Ixtapa/Zihuatanejo",
    "ZIN" to "Interlaken",
    "ZJS" to "Jena",
    "ZJU" to "Olten",
    "ZKE" to "Kaschechewan",
    "ZKJ" to "Schaffhausen",
    "ZLI" to "Winterthur",
    "ZLJ" to "Yverdon-Les-Bains",
    "ZMG" to "Magdeburg",
    "ZMO" to "Modena/Marzaglia",
    "ZMT" to "Masset",
    "ZNF" to "Hanau",
    "ZNM" to "Herten-Rheinfelden",
    "ZNO" to "Hildesheim",
    "ZNQ" to "Ingolstadt",
    "ZNS" to "Kempten-Durach",
    "ZNV" to "Koblenz-Winningen",
    "ZOA" to "Leverkusen",
    "ZOI" to "Marburg-Schonstadt",
    "ZOJ" to "Marl-Loemuhle",
    "ZOW" to "Nordhorn-Lingen",
    "ZPA" to "Offenburg",
    "ZPD" to "Oldenburg-Hatten",
    "ZPE" to "Osnabruck-Atterheide",
    "ZPG" to "Peine-Eddesse",
    "ZPI" to "Pirmasens",
    "ZPM" to "Regensburg-Oberhub",
    "ZPT" to "Saarlouis-Duren",
    "ZPU" to "Salzgitter-Drutte",
    "ZQC" to "Speyer",
    "ZQD" to "Stade",
    "ZQP" to "Wesel-Romerwardt",
    "ZQV" to "Worms",
    "ZQW" to "Zweibruken",
    "ZRH" to "Zurich",
    "ZRK" to "Rockford",
    "ZSK" to "Pasewalk-Fransfelde",
    "ZSN" to "Stendal-Borstel",
    "ZSO" to "Suhl-Goldlauter",
    "ZSR" to "Schwerin-Parchim",
    "ZST" to "Stewart",
    "ZSU" to "Dessau",
    "ZSX" to "Stralsund",
    "ZTH" to "Zakynthos",
    "ZTK" to "Triengen",
    "ZTM" to "Shamattawa",
    "ZTZ" to "Chemnitz/Jahnsdorf",
    "ZUB" to "Neubrandenburg",
    "ZWM" to "Wismar-Muggenburg",
    "ZXB" to "Jan Mayen",
    "ZXC" to "Bangsund",
    "ZXD" to "Vikna",
    "ZXF" to "Rørvik",
    "ZXG" to "Gravik",
    "ZXH" to "Sørfjord",
    "ZXI" to "Røddey",
    "ZXJ" to "Fore",
    "ZXK" to "Båsmo",
    "ZXL" to "Skjerstad",
    "ZXN" to "Leka",
    "ZXO" to "Fauske",
    "ZXQ" to "Solstad",
    "ZXR" to "Hemnes",
    "ZZV" to "Zanesville",
)
